// examples/starter-kit/src/widget/index.tsx
import { useContext } from '@datadog/ui-extensions-react';
import { init, EventType } from '@datadog/ui-extensions-sdk';
import './../index.css';
import React from 'react';
import ReactDOM from 'react-dom';

import './widget.css';
import 'typeface-roboto';
import 'milligram';
import { useEffect, useState } from 'react';

const client = init();

function Widget() {
    const context = useContext(client);
    const [metric, setMetric] = useState('system.cpu.idle');
    const [broadcastClickCount, setBroadcastClickCount] = useState(0);

    useEffect(() => {
        if (context !== undefined) {
            setMetric(context.widget?.definition.options?.metric);
        }

        client.events.on(
            EventType.DASHBOARD_CUSTOM_WIDGET_OPTIONS_CHANGE,
            ({ metric }) => {
                if (typeof metric !== 'string') {
                    return;
                }
                setMetric(metric);
            }
        );

        client.events.onCustom('modal_button_click', setBroadcastClickCount);
    }, [context]);

    const onOpenSidePanel = (args: any) => {
        client.sidePanel.open(
            {
                source: 'panel',
                key: 'custom-side-panel',
                title: 'Custom Sidepanel'
            },
            { metric }
        );
    };

    return (
        <section style={{ padding: '10px' }}>
            <h2>Hello App Developer! 👋</h2>
            <p>Welcome to your first Datadog application.</p>
            <p>
                Your favorite metric is: <strong>{metric}</strong>
            </p>
            <p>
                You can open a side panel programatically and pass to it your
                favorite metric by clicking{' '}
                <button
                    className="button button-outline"
                    onClick={onOpenSidePanel}
                >
                    here
                </button>{' '}
            </p>
            <p>
                The red button in the modal has been clicked:{' '}
                <strong>{broadcastClickCount}</strong> time(s)
            </p>
        </section>
    );
}

export default function render() {
    ReactDOM.render(
        <React.StrictMode>{<Widget />}</React.StrictMode>,
        document.getElementById('root')
    );
}

// examples/vue-custom-widget/src/views/Widget.vue
<template>
    <section>
        <h2>Hello App Developer! 👋</h2>
        <p>Welcome to your first Datadog application.</p>
        <p>
            Your favorite metric is: <strong>{{ metric }}</strong>
        </p>
    </section>
</template>

<script>
import { EventType, init } from '@datadog/ui-extensions-sdk';
import 'milligram';
import 'typeface-roboto';

const client = init();

export default {
    name: 'Widget',
    data() {
        return {
            metric: 'system.cpu.idle',
            $_unsubscribe: undefined
        };
    },
    mounted() {
        client.getContext().then(context => {
            this.metric = context.widget?.definition.options?.metric;
        });

        this.$_unsubscribe = client.events.on(
            EventType.DASHBOARD_CUSTOM_WIDGET_OPTIONS_CHANGE,
            options => {
                if (typeof options.metric !== 'string') {
                    return;
                }

                this.metric = options.metric;
            }
        );
    },
    beforeUnmount() {
        this.$_unsubscribe?.();
    }
};
</script>

<style scoped>
section {
    padding: 10px;
}
</style>
